### ISSUE TITLE
pprn 3000 never starts

### ISSUE THREAD

**Issue by alfonsop123** [pluja/blogo#24]
### What happened?

It said starting port 3000

### Operating System

Linux

### Relevant log output

```shell
Last login: Sat Jul 20 15:40:00 2024
alfonsop123@raspberrypi:~ $ sudo docker run docker-conpose.yml
Unable to find image 'docker-conpose.yml:latest' locally
docker: Error response from daemon: pull access denied for docker-conpose.yml, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
alfonsop123@raspberrypi:~ $ sudo docker run pluja/blogo:latest
1:19AM INF Using path: /app
1:19AM WRN No .env file found, using default settings or environment variables.
11:19PM INF Loaded settings:
11:19PM INF     ~ Title: Blogo
11:19PM INF     ~ Description: Welcome to my Blogo 🎈
11:19PM INF     ~ Url: http://localhost:3000
11:19PM INF     ~ Keywords: blog, blogo
11:19PM INF     ~ Timezone: UTC
11:19PM INF Starting server on port 3000...
```

### Code of Conduct

- [X] I have searched for simmilar issues
- [X] I am sure my issue is related to blogo
- [X] I have searched for the error message on the internet

**Comment by pluja** [comment]
I can't assist you. You don't even read the errors. This has 0 relation to blogo. I am blocking you from opening any more issues, since none are useful and you only seek for someone to solve your problems. I don't have time for this, sorry. I am sure you can use some AI to guide you through this, or just search the internet.

Some hints:

- the file is named docker-conpose.yml (notice the n)
- you are using docker run for a docker compose project
- you should read the error instead of just copy pasting it here
