### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alfonsop123** [pluja/blogo#7]
How do i do it on a rpi4 with raspberry pi os bit 64?
I did everything but did not work so I adjusted to using 
sudo docker run --name blogo -v $(pwd)/articles:/app/articles -p 3000:3000 arm32v7/node:14
And idk how to fix it cause it does not run on port 3000 (localhost:3000)

**Comment by pluja** [comment]
The app is not made with node, so I don't think it will work. Could you share whatever error you were getting so I can try find a solution?

**Comment by alfonsop123** [comment]
chevron_right

docker run --name blogo -v $(pwd)/articles:/app/articles -p 3000:3000 pluja/blogo -d

docker: Error response from daemon: Conflict. The container name "/blogo" is already in use by container "ccbca129790d7d661f3891ea005a95dd35ed798e7731302957f6ddaae2d56a9c". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

chevron_right

sudo docker run --name blogo -v $(pwd)/articles:/app/articles -p 3000:3000 pluja/blogo -d

docker: Error response from daemon: Conflict. The container name "/blogo" is already in use by container "ccbca129790d7d661f3891ea005a95dd35ed798e7731302957f6ddaae2d56a9c". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by alfonsop123** [comment]
Then I tried this but still
docker rm blogo

blogo

chevron_right

docker run --name blogo -v $(pwd)/articles:/app/articles -p 3000:3000 pluja/blogo -d

docker: Error response from daemon: create $(pwd)/articles: "$(pwd)/articles" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by pluja** [comment]
The issue is with this: `create (pwd)/articles" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.`

can you run:

`docker rm blogo`

Then (note the qutoing around the volume definition):

`docker run --name blogo -v "$(pwd)/articles:/app/articles" -p 3000:3000 pluja/blogo -d`

**Comment by alfonsop123** [comment]
What volume do I put then as in the storage cap? Sowy I'm confused here I'm new to docker

**Comment by alfonsop123** [comment]
Anyone know?

**Comment by pluja** [comment]
Hi, I don't quite understand your question. Please:

1. Stop and remove all blogo containers that you have. You can use this command:

```bash
docker ps -a | grep "blogo" | awk '{print $1}' | xargs -r docker rm -f
```

2. Repeat the self-hosting steps as stated in the [readme.md](https://github.com/pluja/blogo?tab=readme-ov-file#self-hosting)

Get back if you have any further issues.

**Comment by alfonsop123** [comment]
like you said to read the pwd so like idk what to put there

**Comment by alfonsop123** [comment]
also

alfonsop123@raspberrypi:~ $ docker ps -a | grep "blogo" | awk '{print $1}' | xargs -r docker rm -f
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
alfonsop123@raspberrypi:~ $ sudo docker ps -a | grep "blogo" | awk '{print $1}' | xargs -r docker rm -f
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/702f3b43bd61?force=1": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/5587f40d1b7e?force=1": dial unix /var/run/docker.sock: connect: permission denied
alfonsop123@raspberrypi:~ $

**Comment by pluja** [comment]
I am sorry, but I can't assist you further. It appears that there is a misunderstanding here. To resolve the error, please carefully read the message it provides as the solution often lies there. I can't be a support team for generic Linux issues, since it's very inefficient and time-consuming. A simple web search will give you the solution: https://is.gd/cUheno

I’m here to help with issues specific to blogo. For other problems, I recommend using resources like Stack Overflow or a quick web search. Learning to research and resolve issues independently will be more beneficial in the long run.

I tried to reproduce your issue locally, but following the steps I am able to host blogo locally without issues. If you have any problems that are directly related to blogo, please share and I will try to assist.

**Comment by alfonsop123** [comment]
This is not completed, its still pending...
